Java portfolio
whiteWolfx99/Portfolio pull request #10
Opened 2022-10-10 22:17 UTC by whiteWolfx99

# Portfolio project

### Description
- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.
- No linters errors

### Thanks

2022-10-10 23:46 UTC, codecaiine requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Project works as expected :heavy_check_mark: 
- No linters errors :heavy_check_mark: 
- Good commits history :heavy_check_mark: 

## Required Changes ♻️
- [ ] Please make your pr title more descriptive in order to tell us what your are doing in your current PR :smile: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-10 23:46 UTC, codecaiine commented on index.html
> +      </div>
- [ ] Good job so far your mobile menu works as expected :clap: However there are some issues with your design :cry: Please make sure that your menu option underline is smaller like the one on the Figma template. Please make ensure you that your menu Xmark has the same size, color, and position as defined on the Figma template. Make sure that your menu fits the mobile version...   because as a developer it is important to pay attention to details and stick to the chosen template as much as possible :smile:

![Screenshot from 2022-10-10 23-09-10(1)](https://user-images.githubusercontent.com/6615394/194965611-c4cc7a1d-2e45-4ca0-826e-88c21812f341.jpg)


#### Figma Design
![Screenshot from 2022-09-14 10-09-31](https://user-images.githubusercontent.com/6615394/190126769-13750d4f-23ba-4953-af17-bc64c40a83b4.png)

- [ ] Your menu is misbehaved, it does not align as expected :cry: Please make sure that your menu is similar to the Figma template heck the recorded video to see the differences :arrow_down: 
https://www.loom.com/share/012fe2e734c94612b5c39b7f21792210

2022-10-10 23:46 UTC, codecaiine commented on README.md
>  ## Images
- [ ] Please try to remove some unnecessary information from your readme and keep only the main header section and don't forget to add the current project details and the different author in order to make your readme more professional :+1:

2022-10-11 13:59 UTC, ichala approved these changes
Hi @whiteWolfx99 ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  

 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️  


 Good job implementing the required changes :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-11 14:01 UTC, merged