Done
whiteWolfx99/Portfolio pull request #2
Opened 2022-09-23 17:20 UTC by whiteWolfx99

# Portfolio Mobile Version Project

## Requirements
- There are no linter errors.
- I used correct GitHub Flow.
- Writing documents in a professional way.
- It have all HTML/CSS requirements.
- It have all Project requirements.

## Thank You.

2022-09-23 18:29 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @whiteWolfx99, I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

- [ ] I am sure you spent a lot of time working on this part but, :smiling_face_with_tear:  it is not part of the requirements yet. Kindly remove it :grin:  . You will work on it later with better material. :+1: 

                        <input placeholder="Full Name">
                            <img class="Section-Gray-Lines" src="./images/Rectangle.png" alt="Section-Gray-Lines">
                
                        <input placeholder="Email">
                        <img class="Section-Gray-Lines" src="./images/Rectangle.png" alt="Section-Gray-Lines">


                        <textarea class="Section-Four-comment"
                            rows="5" placeholder="Enter text here"></textarea>




                   
                            <button  class="Section-Four-Buttom">Get in touch</button>
 




            <img class="Section-Gray-Line" src="./images/Rectangle.png" alt="Section-Gray-Line">




            <ul class="SocialMedia-Second">
                <li><a href=""><img class="SocialMedia-Second-images" src="./images/github.png"
                            alt="github"></a></li>
                <li><a href=""><img class="SocialMedia-Second-images" src="./images/linkedin.png"
                            alt="Linkedin"></a></li>
                <li><a href=""><img class="SocialMedia-Second-images" src="./images/Peace.png"
                            alt="Peace"></a></li>
                <li><a href=""><img class="SocialMedia-Second-images" src="./images/twitter.png"
                            alt="twitter"></a></li>
                <li><a href=""><img class="SocialMedia-Second-images" src="./images/M.png"
                            alt="M"></a></li>
            </ul>
            <img class="Iphone-line" src="./images/Shape.png" alt="">
        </div>


- [ ]  Kindly make sure your body takes the max screen so that it will remove the scrolling button below and your design will stick perfectly to the Figma design :+1: :grinning: :grinning: :grinning:

 ## Your design

![Screenshot_20220923_183730](https://user-images.githubusercontent.com/95297251/192035603-c2961085-3d1d-4818-a081-15bfa4d869a5.png)

 ## Figma design

![image](https://user-images.githubusercontent.com/95297251/192036522-e117befa-d9d8-4156-b6ef-8c650306dae6.png)

- [ ] Kindly remove this padding-left so that it will align your project image with the rest of your web site as required in the figma design. Check the difference below between your design and the Figma design :grinning: 

## Your design

![image](https://user-images.githubusercontent.com/95297251/192036522-e117befa-d9d8-4156-b6ef-8c650306dae6.png)

## Figma design

![Screenshot_20220923_185115](https://user-images.githubusercontent.com/95297251/192037765-e9b7f32e-cbe2-45cd-bf99-1bf3a57cda21.png)

- [ ] The container of the section is a `section` tag. Kindly replace the `<div>` tag by the `<section> `tag :grinning: :grinning: :grinning: . It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info. 
        <div class="Section-two">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] [OPTIONAL] Please make sure that all your changes are visible in your current pull request so that your code reviewer could see the changes you have done.
- [ ] [OPTIONAL] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-23 18:38 UTC, whiteWolfx99 commented
I can see Required Changes review

2022-09-23 18:42 UTC, whiteWolfx99 commented
So I have to remove Section 4 entirely ?

2022-09-23 19:06 UTC, whiteWolfx99 commented
Check out the requirements I completed.

2022-09-23 23:41 UTC, Olamarx requested changes
Hi @whiteWolfx99, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>

 ## Highlights
- Descriptive PR ✔️ 
- Linters passed ✔️ 
- Good use of Git and Github flow ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 23:41 UTC, Olamarx commented on styless.css
>  }
- [ ] Kindly remove the margin left since you used justify content already.
## Your design
![image](https://user-images.githubusercontent.com/86200356/192069035-15e5da12-cfcf-4f9c-bcce-fe872b6e3b07.png)
## The look when I removed the margin left
![image](https://user-images.githubusercontent.com/86200356/192069100-3c933a16-0ae0-4546-a8fd-c5d46d20b4ae.png)

2022-09-23 23:41 UTC, Olamarx commented on index.html
> +                    <h2 class="Section-two-Title">My Recent Works</h2>
- [ ] Kindly stick to the figma design in fonts, color etc.
- [ ]  This is the view of your design in the minimum width requirement (375px)
![image](https://user-images.githubusercontent.com/86200356/192069420-692d1e0a-f1dd-449a-94db-a55bef309fd2.png)
- [ ] The figma design
![image](https://user-images.githubusercontent.com/86200356/192069551-50398df9-daff-43a3-82ff-9978ce6a19ab.png)

2022-09-23 23:41 UTC, Olamarx commented on index.html
> +
[OPTIONAL] I would suggest you remove these empty spaces as they won't make your codebase neat.

2022-09-24 00:52 UTC, NduatiKagiri approved these changes
## Status: Approved 💯 

Hi @whiteWolfx99 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

✔️ Descriptive PR
✔️ Linters are passing

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 09:30 UTC, merged